FROM ubuntu:14.04

MAINTAINER youyongsong@gmail.com

RUN apt-get update && \
    apt-get install -y build-essential \
        golang \
        git \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get -y autoclean
