FROM golang:1.7

MAINTAINER youyongsong@gmail.com

RUN apt-get update && \
    apt-get install -y build-essential \
        git python2.7 python-pip \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get -y autoclean

RUN pip install awscli
